### ISSUE TITLE
Configure HTTP client timeouts

### ISSUE THREAD

**Issue by dnnrly** [dnnrly/wait-for#7]
**Is your feature request related to a problem? Please describe.**
At the moment, the HTTP client is hard-coded to time out after 1 second. This means that if you have an application that always takes longer than a second to respond, it will never be marked as successful.

**Describe the solution you'd like**
It would be good if we could set the HTTP timeout in both the config file for each target AND using the target in the args.

**Comment by kkupreeva** [comment]
Hello @dnnrly 
Attempted to solve this issue. Please take a look ([PR](https://github.com/dnnrly/wait-for/pull/12)).

**Comment by dnnrly** [comment]
Fixed by #12
