### ISSUE TITLE
Add a docker compose example

### ISSUE THREAD

**Issue by dnnrly** [dnnrly/wait-for#8]
**Is your feature request related to a problem? Please describe.**
If you look _really_ closely at the README, you can see a localstack compatible example, which is where wait-for really shines. It would be good to make this explicit so that people can search for a solution and find this. And also so I can have something to refer to when I use it again in the future.

**Describe the solution you'd like**
Maybe just something a little clearer in the README.

**Comment by jesselang** [comment]
Seems like a docker-compose example was added in https://github.com/dnnrly/wait-for/commit/471fcd7b5bc50b4cac799ee5d5255e795ed01d43 . Correct?

**Comment by dnnrly** [comment]
Yes, you're right - we'll spotted!
